### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by anmolnagpal**

### CODE REVIEW

**Comment by tecris** [comment]
Hi,
Thank you for the pull request.
Can you please provide an official link (from ansible) that states import_tasks is preferred over include?

thanks again

**Comment by anmolnagpal** [comment]
Here is the link 
http://docs.ansible.com/ansible/latest/modules/import_tasks_module.html

**Comment by tecris** [comment]
OK, it seems the include task is deprecated:
"The bare include task (which was used for both Task files and Playbook-level includes) is still available, however it is now considered deprecated."
http://docs.ansible.com/ansible/devel/user_guide/playbooks_reuse.html#dynamic-vs-static

Yet, there are two new tasks import_tasks and include_tasks, with some comments here:
http://docs.ansible.com/ansible/devel/user_guide/playbooks_reuse.html#dynamic-vs-static

Need to read more.
thanks

**Comment by tecris** [comment]
Using import_task module requires to update min ansible version from 2.0 to 2.4. Currently versions 2.4 and 2.5 are supported.

**Comment by tecris** [comment]
To reopen, merge didn happened

**Comment by tecris** [comment]
anmolnagpal, can you pls resubmit the pull request?
Not sure what I've done, yet, the pull request did not merged :(

**Pull request closed without merging**
